apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-baseline
  labels:
    app: detection-baseline
spec:
  replicas: 2
  selector:
    matchLabels:
      app: detection-baseline
  template:
    metadata:
      labels:
        app: detection-baseline
    spec:
      containers:
      - name: model-baseline
        image: secure-ai-detection:baseline
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "2Gi"
            cpu: "1"
          requests:
            memory: "1Gi"
            cpu: "500m"
